[package]
name = "globalvpn"
version = "0.1.0"
authors = ["Raphael Peters <rappet@rappet.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
env_logger = "0.7.1"
async-std = "1.6.2"
sodiumoxide = "0.2.6"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5.6"
chrono = "0.4.13"
bytes = "0.5.6"
