[package]
name = "globalvpn"
version = "0.1.0"
authors = ["Raphael Peters <rappet@rappet.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.log]
version = "0.4.14"

[dependencies.env_logger]
version = "0.8.3"

[dependencies.thiserror]
version = "1.0.24"

[dependencies.anyhow]
version = "1.0.38"

[dependencies.derive_more]
version = "0.99.11"

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.serde]
version = "1.0.124"
features = ["derive"]

[dependencies.bytes]
version = "1.0.1"

[dependencies.smallvec]
version = "1.6.1"
features = ["serde", "union"]

[dependencies.sodiumoxide]
version = "0.2.6"
features = ["serde"]

[dependencies.tokio]
version = "1.3.0"
features = ["full"]

